import { AgeGroup } from "./age-group";
import { Availability } from "./availability";
import { Certification } from "./certification";
import { Condition } from "./condition";
import { DateRange } from "./date-range";
import { EnergyEfficiencyClass } from "./energy-efficiency-class";
import { Gender } from "./gender";
import { Installment } from "./installment";
import { LoyaltyPoints } from "./loyalty-points";
import { Price } from "./price";
import { SubscriptionCost } from "./subscription-cost";
import { Tax } from "./tax";
import { ValueWithUnit } from "./value-with-unit";
import { YesNo } from "./yes-no";

export type Product = {
  id?: string;
  title?: string;
  link?: string;
  imageLink?: string;
  additionalImageLinks?: string[];
  mobileLink?: string;
  availability?: Availability.Model;
  availabilityDate?: Date;
  costOfGoodsSold?: Price.Model;
  expirationDate?: Date;
  price?: Price.Model;
  salePrice?: Price.Model;
  salePriceEffectiveDate?: DateRange.Model;
  unitPricingMeasure?: ValueWithUnit.Model;
  unitPricingBaseMeasure?: ValueWithUnit.Model;
  installment?: Installment;
  subscriptionCost?: SubscriptionCost;
  loyaltyPoints?: LoyaltyPoints;
  googleProductCategory?: string;
  productType?: string;
  brand?: string;
  gtin?: string;
  mpn?: string;
  identifierExists?: YesNo | boolean;
  condition?: Condition;
  adult?: YesNo | boolean;
  multipack?: number;
  isBundle?: YesNo | boolean;
  certification?: Certification.Model;
  energyEfficiencyClass?: EnergyEfficiencyClass;
  minEnergyEfficiencyClass?: EnergyEfficiencyClass;
  maxEnergyEfficiencyClass?: EnergyEfficiencyClass;
  ageGroup?: AgeGroup.Model;
  color?: string;
  gender?: Gender;
  material?: string;
  pattern?: string;
  size?: string;
  sizeType?: string;
  sizeSystem?: string;
  itemGroupId?: string;

  tax?: Tax;
};
